emit transaction failed: error_class=NoMethodError error=undefined method dump
Was getting this error:
2017-12-01 19:39:32 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `dump' for #<KubernetesMetadata::Stats:0x000000024b7ce0>\nDid you mean?  dup" tag="kubernetes.var.log.containers.mux-mux.mux-mux_testproj_mux-0123456789012345678901234567890123456789012345678901234567890123.log.mux"

Method should be `bump` instead of `dump`.  I also added some tests
for these lines of code.